name: Generate Contribution Calendar

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  contrib-calendar:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Generate contribution calendar (last 3 years)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}
          filename: github-contribution-calendar.svg
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 3
          config_timezone: America/Sao_Paulo
          output_action: commit
          committer_branch: main
          committer_message: "chore: update contribution calendar"
